---
title: "EFI-NEON Ecological Forecasting Challenge Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: "cosmo"
runtime: shiny
---
```{r setup, include = FALSE}
#remotes::install_deps()
library(flexdashboard)
library(shiny)
library(gganimate)
library(plotly)
library(tidyverse)
library(ncdf4)
library(scales)
library(readr)
library(DT)
library(gsubfn)
library(tools)
```

Visualize Forecast Submissions
=======================================================================

Pick Forecast Category {.sidebar}
-----------------------------------------------------------------------

```{r}
#THIS FILE PATH NEEDS TO BE CHANGED - currently set to my local files
base.dir = '~/efi_neon_challenge/forecasts/'
target.dir = "~/efi_neon_challenge/targets/"

fnames <- tibble(files = list.files(path = base.dir, recursive = TRUE, full.names = TRUE)) %>% 
  filter(file_ext(files) %in% c("nc","csv")) %>% 
  filter(!str_detect(files, "not_in_standard")) %>% 
  mutate(basename = basename(files))

data <- unlist(str_split_fixed(tools::file_path_sans_ext(fnames$basename), pattern = "-", 5)) %>% 
  as_tibble() %>% 
  unite("date", V2:V4, sep = "-") %>% 
  rename("theme" = V1,
         "team" = V5) %>% 
  bind_cols(fnames) %>% 
  select(-basename)

theme_choices <- c("aquatics", 
                   "beetles", 
                   "phenology", 
                   "terrestrial_30min", 
                   "terrestrial_daily", 
                   "ticks")

#need target vars for nc file var get 
target_variables <- c("oxygen", 
                      "temperature", 
                      "richness", 
                      "abundance", 
                      "nee", 
                      "le", 
                      "vswc", 
                      "gcc_90", 
                      "ixodes_scapularis", 
                      "amblyomma_americanum")

renderUI({
  selectInput("forecast", "Forecast theme:", 
              choices = theme_choices, selected = "phenology")
})


#based on choice above, reads file in dir and creates new inputs to select from 

files <- reactive({
  if(!is.null(input$forecast)){
    fnames <- list.files(path = base.dir, recursive = TRUE, full.names = TRUE, pattern = input$forecast)
    fnames[which(file_ext(fnames) %in% c("nc", "gz", "csv"))]
    d <- fnames[!stringr::str_detect(fnames, "not_in_standard")]
    d
  }else{
    NULL
  }
})

file.date <- reactive({
  if(!is.null(files())){
    d <- lubridate::as_date(strapplyc(basename(files()), pattern = "[0-9-]{8,}", simplify = TRUE) %>% 
                              gsub("-$", "", .) %>% 
                              gsub("^-", "", . ))
    
    d <- sort(d[!is.na(d)], decreasing = TRUE)
    d
  }else{
    NULL
  }
  
})

#file selection 
renderUI({
  selectInput('date', 'Select First Date of Forecast:',
              choices = file.date(), selected = lubridate::as_date("2021-03-05"))
})

files_with_date <- reactive({
  if(!is.null(files()) & !is.null(input$date)){
    if(input$date == ""){
    fnames <- files()[stringr::str_detect(files(), pattern = "2021-03-05")]
    fnames[which(file_ext(fnames) %in% c("nc", "gz", "csv"))]
    }else{
       fnames <- files()[stringr::str_detect(files(), pattern = input$date)]
    fnames[which(file_ext(fnames) %in% c("nc", "gz", "csv"))]
    }
  }else{
    NULL
  }
})

file.model <-  reactive({
  if(!is.null(files_with_date())){
    files_with_date() %>% 
      str_extract(., "\\-[[:alpha:]](.*?)\\.") %>% 
      gsub("^-", "", .) %>% 
      gsub(".$","",.)
  }else{
    NULL
  }
})

renderUI({
  selectInput('model', 'Select Model:',
              #choices = file.model(), selected = file.model()[1], multiple = FALSE)
              choices = file.model(), selected = "EFInull", multiple = FALSE)
})

file.path <- reactive({
  if(!is.null(files_with_date())){
    files_list <- NULL
    for(i in 1:length(input$model)){
      files_list <- c(files_list, files_with_date()[grep(input$model[i], files_with_date())])
    }
    files_list
  }else{
    NULL
  }
})

#reads selected data 
data <- reactive({
  
  fnames <- file.path()
  
  team_name <-   fnames %>% 
    str_extract(., "\\-[[:alpha:]](.*?)\\.") %>% 
    gsub("^-", "", .) %>% 
    gsub(".$","",.)
  
  d2 <- NULL
  
  if(!is.null(fnames)){
  
  for(k in 1:length(fnames)){
    
    if(file_ext(fnames[k]) %in% c("gz","csv")){  #if file is csv zip file
      if(input$forecast == "ticks"){
        d <- as.data.frame(read_csv(fnames[k], guess_max = 100000))
      }else{
        d <- as.data.frame(read_csv(fnames[k], guess_max = 100000)) %>% 
          filter(time >= input$date)
      }
      if("plotID" %in% names(d)){
        d <- d %>% mutate(siteID = plotID)
      }else{
        d
      }
    }else if(file_ext(fnames[k]) == "nc"){ #if file is nc
      
      nc <- ncdf4::nc_open(fnames[k])
      siteID <- ncdf4::ncvar_get(nc, "siteID")
      time <- ncdf4::ncvar_get(nc, "time")
      siteID <- ncdf4::ncvar_get(nc, "siteID")
      time <- ncdf4::ncvar_get(nc, "time")
      t_string <- strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")[[1]]
      if(t_string[1] == "days"){
        tustr<-strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")
        time <-lubridate::as_date(time,origin=unlist(tustr)[3])
      }else{
        tustr <- lubridate::as_datetime(strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")[[1]][3])
        time <- as.POSIXct.numeric(time, origin = tustr)
      }
      
      team <- ncdf4::ncatt_get(nc, varid = 0, "forecast_project_id")$value
      targets = names(nc$var)[which(names(nc$var) %in% target_variables)]
      
      combined_forecast <- NULL
      for(j in 1:length(targets)){
        forecast_targets <- ncdf4::ncvar_get(nc, targets[j])
        for(i in 1:length(siteID)){
          tmp <- forecast_targets[ ,i ,]
          d <- cbind(time, as.data.frame(tmp))
          names(d) <- c("time", seq(1,dim(tmp)[2]))
          d <- d %>%
            tidyr::pivot_longer(-time, names_to = "ensemble", values_to = "value") %>%
            dplyr::mutate(siteID = siteID[i],
                          variable = targets[j])
          combined_forecast <- rbind(combined_forecast, d)
        }
      }
      ncdf4::nc_close(nc)
      combined_forecast <- combined_forecast %>%
        tidyr::pivot_wider(names_from = variable, values_from = value)
      
      d <- as.data.frame(combined_forecast) 
    }
    d <- d %>% mutate(team = team_name[k])
    d2 <- dplyr::bind_cols(d2, d)
  }
  }
  d2
})

### NEW ###

all_files <- reactive({
  print(data)
  data %>% filter(theme == input$theme)
  
})

#reads selected data 
data_date_model <- reactive({
  
  fnames <- all_files()$files
  team_name <- all_files()$team
  start_date <- all_files()$date
  theme <- all_files()$theme

  d2 <- NULL
  
  if(!is.null(fnames)){
    
    for(k in 1:length(fnames)){
      print(k)
      
      if(file_ext(fnames[k]) %in% c("gz","csv")){  #if file is csv zip file
        if(input$forecast == "ticks"){
          d <- as.data.frame(read_csv(fnames[k], guess_max = 100000))
        }else{
          d <- as.data.frame(read_csv(fnames[k], guess_max = 100000)) %>% 
            filter(time >= input$date)
          
          print(d)
          
          
        }
        if("plotID" %in% names(d)){
          d <- d %>% mutate(siteID = plotID)
        }else{
          d
        }
        
      }else if(file_ext(fnames[k]) == "nc"){ #if file is nc
        
        nc <- ncdf4::nc_open(fnames[k])
        siteID <- ncdf4::ncvar_get(nc, "siteID")
        time <- ncdf4::ncvar_get(nc, "time")
        siteID <- ncdf4::ncvar_get(nc, "siteID")
        time <- ncdf4::ncvar_get(nc, "time")
        t_string <- strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")[[1]]
        if(t_string[1] == "days"){
          tustr<-strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")
          time <-lubridate::as_date(time,origin=unlist(tustr)[3])
        }else{
          tustr <- lubridate::as_datetime(strsplit(ncdf4::ncatt_get(nc, varid = "time", "units")$value, " ")[[1]][3])
          time <- as.POSIXct.numeric(time, origin = tustr)
        }
        
        team <- ncdf4::ncatt_get(nc, varid = 0, "forecast_project_id")$value
        targets = names(nc$var)[which(names(nc$var) %in% target_variables)]
        
        combined_forecast <- NULL
        for(j in 1:length(targets)){
          forecast_targets <- ncdf4::ncvar_get(nc, targets[j])
          for(i in 1:length(siteID)){
            tmp <- forecast_targets[ ,i ,]
            d <- cbind(time, as.data.frame(tmp))
            names(d) <- c("time", seq(1,dim(tmp)[2]))
            d <- d %>%
              tidyr::pivot_longer(-time, names_to = "ensemble", values_to = "value") %>%
              dplyr::mutate(siteID = siteID[i],
                            variable = targets[j])
            combined_forecast <- rbind(combined_forecast, d)
          }
        }
        ncdf4::nc_close(nc)
        combined_forecast <- combined_forecast %>%
          tidyr::pivot_wider(names_from = variable, values_from = value)
        
        d <- as.data.frame(combined_forecast) 
      }

      d <- d %>% mutate(team = team_name[k])

      ## add missing optional columns
      if(!("forecast_start_time" %in% colnames(d)))
        d <- d %>% mutate(forecast_start_time = start_date[k])
      if(!("theme" %in% colnames(d))) 
        d <- d %>% mutate(theme = theme[k])
            
      ### organize so data can be combined  **** need to generalize to drop gcc_90 ****
      if("ensemble" %in% colnames(d)){
        d <- d %>% 
          group_by(time, siteID, forecast_start_time, team, theme) %>% 
          summarise(mean = mean(gcc_90, na.rm = TRUE),
                    sd = sd(gcc_90, na.rm = TRUE),
                    upper95 = quantile(gcc_90, 0.975, na.rm = TRUE),
                    lower95 = quantile(gcc_90, 0.025, na.rm = TRUE)) %>% 
          pivot_longer(cols = c("mean","sd", "upper95","lower95"), names_to = "statistic", values_to = "gcc_90") %>% 
          select(time, siteID, forecast_start_time,  team, theme, statistic, gcc_90)
      }else{
        d <- d %>% 
          select(time, siteID, forecast_start_time, team, theme, statistic, gcc_90) %>% 
          pivot_wider(names_from = statistic, values_from = gcc_90, values_fn = mean) %>% 
          mutate(upper95 = mean + 1.96 * sd,
                 lower95 = mean - 1.96 * sd) %>% 
          pivot_longer(cols = c("mean","sd", "upper95","lower95"), names_to = "statistic", values_to = "gcc_90")
      }
      
      ### combine
      d2 <- rbind(d2, d)
    }
  }
  print(d2)
  d2
})

### OLD ####

sites <- reactive({
  if(!is.null(data())){
    unique(data()$siteID)
  }
})

plots <- reactive({
  if(!is.null(data())){
  if(length(unique(data()$plotID)) > 0){
    unique(data()$plotID)
  }else{
    NA
  }
  }
})

x_axis_variables <- c("time")

y.inputs <- reactive({
  if(!is.null(data())){
    vars <- names(data())
    vars[which(vars %in% target_variables)]
  }
})

renderUI({
  selectInput('y.var', "Select Variable for Y-Axis:", 
              choices = y.inputs(), selected = y.inputs()[1])
              #choices = y.inputs())
})

renderUI({
  selectInput('site', "Select Sites:",
              choices = c(sites()), selected = sites()[1],multiple = TRUE)
})

sub.data <- reactive({
  if(!is.null(data())){
    data() %>% 
      filter(siteID %in% input$site)
  }else{
    NULL
  }
})


target.file <- reactive({
  list.files(path = paste0(target.dir), recursive = TRUE, pattern = input$forecast, full.names = TRUE)
})

#this is to set up data cleaning for the graphing section
#index.x <- reactive(which(names(sub.data()) == input$x.var))
var.y <- reactive({
  if(!is.null(sub.data())){
    index <- which(names(sub.data()) == input$y.var)
    sub.data()[,index]
  }else{
    NULL
  }
})


```


Forecast Plot 
-------------------------------------

```{r}
#clean data and aggregate for graphing 
data.sum <- reactive({
  
  if(!is.null((sub.data()))){

  if("plotID" %in% names(sub.data())){
    d <- sub.data() %>% mutate(siteID = plotID) 
  }else{
    d <- sub.data()
  }
  
  if("ensemble" %in% colnames(d)){
  
    d %>%
      mutate(var.y = var.y()) %>% 
      group_by(siteID, time, team) %>%
      summarize(med = quantile(var.y, 0.5, na.rm = TRUE),
                upper = quantile(var.y, 0.975, na.rm = TRUE),
                lower = quantile(var.y, 0.025, na.rm = TRUE), .groups = "drop")
  }else{
    
    d1 <- d %>% 
      mutate(var.y = var.y())  %>%  
      select(var.y, "statistic", "time", siteID, team) %>%  
      pivot_wider(names_from = statistic, values_from = var.y) %>%  
      mutate(med = mean,
             upper = mean + 1.96 * sd,
             lower = mean - 1.96 * sd)
  }
  
  }else{
    NULL
  }
})
```


### Forecast and Observed Plot 

```{r}


#target.path = reactive(paste0(target.dir, input$forecast, "/", input$target))

targets<- reactive({
  read_csv(target.file(), guess_max = 100000)
})


#this is to set up data cleaning for the graphing section 
#target.x <- reactive(which(names(targets()) == input$x.var))
target.y <- reactive({
  if(!is.null(input$y.var)){
  which(names(targets()) == input$y.var)
  }else{
    NULL
  }
})

#target.var.x <- reactive(targets()[,target.x()])
target.var.y <- reactive({
  if(!is.null(target.y())){
  targets()[,target.y()]
  }else{
    NULL
  }
  })

targets.sum <- reactive({
  
  if(!is.null(data.sum()) & !is.null(target.var.y())){
    
    if("plotID" %in% names(targets())){
      d <- targets() %>% mutate(siteID = plotID)
    }else{
      d <- targets() 
    }
    d %>%
      mutate(var.y =  unlist(target.var.y())) %>%  
      filter(siteID %in% input$site)
  }else{
    NULL
  }
})


combo <- reactive({
  
  if(!is.null(data.sum()) & !is.null(targets.sum())){
  
  left_join(data.sum(),targets.sum(), by = c("time", "siteID"), suffix = c('_data', '_target'))
  }else{
    NULL
  }
  
})


target.plot <- reactive({
  
  if(!is.null(combo())){
    
    if(nrow(combo()) > 0){
    
    if(input$forecast != "terrestrial_30min"){
      if(!all(is.na(combo()$var.y))){
        ggplot(data = combo(), aes(y = med, x = time)) + 
          geom_line(data = combo(), aes(x = time, y = med, color = "Forecast (Median)")) + 
          geom_ribbon(aes(x = time, ymin = lower, ymax = upper, fill = "Forecast (95% CI)"), alpha = 0.4) +
          geom_point(data = combo(), aes(x =time, y = var.y, color = "Target"), size = 1.5) + 
          scale_x_date(labels = date_format("%Y-%m-%d")) +
          labs(x = "time", y = input$y.var) +
          facet_wrap(~siteID)
      }else{
        ggplot(data = data.sum(), aes(y = med, x = time)) + 
          geom_line(data = data.sum(), aes(x =time, y = med, color = "Forecast (Median)")) + 
          geom_ribbon(aes(x = time, ymin = lower, ymax = upper, fill = "Forecast (95% CI)"), alpha = 0.4) +
          #scale_fill_discrete(name = input$group) + 
          scale_x_date(labels = date_format("%Y-%m-%d")) +
          labs(x = "time", y = input$y.var) +
          facet_wrap(~siteID)
      }
    }else{
      if(!all(is.na(combo()$var.y))){
        ggplot(data = combo(), aes(y = med, x = time)) + 
          geom_line(data = combo(), aes(x = time, y = med, color = "Forecast (Median)")) + 
          geom_ribbon(aes(x = time, ymin = lower, ymax = upper, fill = "Forecast (95% CI)"), alpha = 0.4) +
          geom_point(data = combo(), aes(x =time, y = var.y, color = "Target"), size = 1.5) + 
          #scale_x_date(labels = date_format("%Y-%m-%d")) +
          labs(x = "time", y = input$y.var) +
          facet_wrap(~siteID)
      }else{
        ggplot(data = data.sum(), aes(y = med, x = time)) + 
          geom_line(data = data.sum(), aes(x =time, y = med, color = "Forecast (Median)")) + 
          geom_ribbon(aes(x = time, ymin = lower, ymax = upper, fill = "Forecast (95% CI)"), alpha = 0.4) +
          #scale_fill_discrete(name = input$group) + 
          #scale_x_date(labels = date_format("%Y-%m-%d")) +
          labs(x = "time", y = input$y.var) +
          facet_wrap(~siteID)
      }
    }
    }
  }
})


renderPlot({
  
  target.plot()
  
})




```



### Historical Time-series of Target

```{r}

#plot full target plot 
renderPlot({
  
  if(!is.null(targets.sum())){
    if(nrow(targets.sum()) > 0){
    ggplot(data = targets.sum()) + 
      geom_point(aes(x = time, y = var.y, color = "Observed Data")) + 
      facet_wrap(~siteID) + 
      #scale_x_date(date_breaks = "6 month", date_labels =  "%b %Y") +
      labs(x = "time", y = input$y.var)
    }
  }
})

```

Scores
=======================================================================

Pick Forecast Category {.sidebar}
-----------------------------------------------------------------------

```{r}
#THIS FILE PATH NEEDS TO BE CHANGED - currently set to my local files
files2 <-  list.files("/efi_neon_challenge/scores", recursive = TRUE, full.names = TRUE, pattern = "[.]csv")

get_scores <- function(files){
  teams_tmp <- (str_split(basename(files), c("-")))
  score <- NULL
  for(i in 1:length(teams_tmp)){
    curr_score <- readr::read_csv(files[i]) %>% 
      dplyr::mutate(score = as.numeric(score),
                    time = lubridate::as_datetime(time),
                    forecast_start = lubridate::as_date(forest_start_time))
    
    
    if(nrow(curr_score) > 0){
      score <- bind_rows(score, curr_score)
    }
  }
  return(score)
}


#score <- get_scores(files2)

renderUI({
  selectInput("theme", "Forecast theme:", 
              choices = theme_choices, selected = "phenology")
})

scores_theme <- reactive({
  d <- files2[stringr::str_detect(files2, input$theme)]
  score <- get_scores(d)
  score %>% filter(theme == input$theme)})

vars.score <- reactive({
  unique(scores_theme()$target)
})

renderUI({
  
  selectInput('target.var', "Select Target Variable:", 
              choices = vars.score(), selected = vars.score()[1])
  
})

scores_theme_target <- reactive({
  scores_theme() %>% filter(target == input$target.var)
})

vars.horizon <- reactive({
  unique(scores_theme_target()$horizon)
})

renderUI({
  
  selectInput('summary.var', "Summarize score by:", 
              choices = c("no summary",  "horizon","siteID", "forecast start date","all"), selected = "no summary")
  
})


scores_theme_target_horizon <- reactive({
  
  if(input$summary.var == "no summary"){
    scores_theme_target() %>% 
      select(theme, target, siteID, time, forecast_start, horizon, team, score) %>% 
      mutate(score = round(score, 5))
    
  }else if(input$summary.var == "horizon"){
    scores_theme_target() %>% 
      select(-time) %>% 
      group_by(siteID, target, theme, team, forecast_start) %>% 
      summarize(score = mean(score, na.rm = TRUE), .groups = "drop") %>% 
      mutate(horizon = "all") %>% 
      mutate(score = round(score, 5)) %>% 
      select(theme, target, siteID, forecast_start, horizon, team, score)
  }else if(input$summary.var == "siteID"){
    scores_theme_target() %>% 
      select(-time) %>% 
      group_by(target, horizon, theme, team, forecast_start) %>% 
      summarize(score = mean(score, na.rm = TRUE), .groups = "drop") %>% 
      mutate(siteID = "all") %>% 
      mutate(score = round(score, 5)) %>% 
      select(theme, target, siteID, forecast_start, horizon, team, score)
  }else if(input$summary.var == "forecast start date"){
    scores_theme_target() %>% 
      select(-time) %>% 
      group_by(target, horizon, theme, team, siteID) %>% 
      summarize(score = mean(score, na.rm = TRUE), .groups = "drop") %>% 
      mutate(forecast_start = "all") %>% 
      mutate(score = round(score, 5)) %>% 
      select(theme, target, siteID, forecast_start, horizon, team, score)
  }else if(input$summary.var == "all"){
    scores_theme_target() %>% 
      select(-time) %>% 
      group_by(target, theme, team) %>% 
      summarize(score = mean(score, na.rm = TRUE), .groups = "drop") %>% 
      mutate(forecast_start = "all",
             siteID = "all",
             horizon = "all") %>% 
      mutate(score = round(score, 5)) %>% 
      select(theme, target, siteID, forecast_start, horizon, team, score)
  }
})

```

Forecast Plot 
-------------------------------------

```{r}
#data.subset <- reactive({
#
#   score() 
# })


```

### Continuous Ranked Probability Score (CRPS) 

```{r}

renderDataTable({
  
  DT::datatable(scores_theme_target_horizon(), options = list(bPaginate = FALSE))
  
})
```